name: Deploy
on:
  push:
    branches: [main]

permissions: {}

jobs:
  deploy:
    if: github.repository == 'enixCode/parpaing-agent-worker'
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: ${{ github.event.repository.name }}
